// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Timescale.Outputs
{

    [OutputType]
    public sealed class GetServiceSpecResult
    {
        /// <summary>
        /// Hostname is the hostname of this service.
        /// </summary>
        public readonly string Hostname;
        /// <summary>
        /// Port is the port assigned to this service.
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Username is the Postgres username.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private GetServiceSpecResult(
            string hostname,

            int port,

            string username)
        {
            Hostname = hostname;
            Port = port;
            Username = username;
        }
    }
}
