// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package timescale

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zlepper/pulumi-timescale/sdk/go/timescale/internal"
)

func GetProducts(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetProductsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetProductsResult
	err := ctx.Invoke("timescale:index/getProducts:getProducts", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getProducts.
type GetProductsResult struct {
	// The ID of this resource.
	Id       string               `pulumi:"id"`
	Products []GetProductsProduct `pulumi:"products"`
}
