// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetProductsProduct {
    description: string;
    /**
     * The ID of this resource.
     */
    id: string;
    name: string;
    plans: outputs.GetProductsProductPlan[];
}

export interface GetProductsProductPlan {
    /**
     * The ID of this resource.
     */
    id: string;
    memoryGb: number;
    milliCpu: number;
    price: number;
    productId: string;
    regionCode: string;
}

export interface GetServiceResource {
    /**
     * Service ID is the unique identifier for this service
     */
    id: string;
    spec: outputs.GetServiceResourceSpec;
}

export interface GetServiceResourceSpec {
    enableHaReplica: boolean;
    memoryGb: number;
    milliCpu: number;
}

export interface GetServiceSpec {
    /**
     * Hostname is the hostname of this service.
     */
    hostname: string;
    /**
     * Port is the port assigned to this service.
     */
    port: number;
    /**
     * Username is the Postgres username.
     */
    username: string;
}

export interface GetVpcsVpc {
    cidr: string;
    created: string;
    errorMessage: string;
    /**
     * The ID of this resource.
     */
    id: number;
    name: string;
    peeringConnections: outputs.GetVpcsVpcPeeringConnection[];
    projectId: string;
    provisionedId: string;
    regionCode: string;
    status: string;
    updated: string;
}

export interface GetVpcsVpcPeeringConnection {
    errorMessage: string;
    /**
     * The ID of this resource.
     */
    id: number;
    peerVpcs: outputs.GetVpcsVpcPeeringConnectionPeerVpc[];
    status: string;
    vpcId: number;
}

export interface GetVpcsVpcPeeringConnectionPeerVpc {
    accountId: string;
    cidr: string;
    /**
     * The ID of this resource.
     */
    id: number;
    regionCode: string;
}

export interface ServiceTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
}

